### PR TITLE
Add support for windows and multiple os

### PR DESCRIPTION
**Pull request by oshai**
will build on windows,linux and mac.

### CODE REVIEW

**Comment by oshai** [comment]
It looks like Java is not supported on windows in Travis, so another alternative is to try circleci.

**Comment by oshai** [comment]
circle ci only support java 11 out of the box, so need to explicitly compile to java 8:
https://stackoverflow.com/questions/49509330/kotlin-compile-to-java-1-8

**Comment by petertrr** [comment]
Hey @oshai , have you considered using github actions for releases? You can use linux, macos and windows runners in the same workflow, and Java versions can be configured using `actions/setup-java`.
I have set up releasing to Maven Central using github actions recently, if you are interested you can check out my config: [PublishingConfiguration.kt](https://github.com/petertrr/kotlin-multiplatform-diff/blob/main/buildSrc/src/main/kotlin/io/github/petertrr/PublishingConfiguration.kt), [release.yml](https://github.com/petertrr/kotlin-multiplatform-diff/blob/main/.github/workflows/release.yml).

**Comment by oshai** [comment]
implemented in another cl in `2.1.15`

**Pull request closed without merging**
