### PR TITLE
Upgrade to Kotlin 1.4-M1 test

### PR DESCRIPTION
**Pull request by rnentjes**
This is a test/example to see how easy it is to create a library with the new IR format introduced in Koltin 1.4-M1.

This works for my scenario, some remarks:

- I needed to upgrade kotlin version to 1.2, compiler no longer supports 1.1
- Used the default naming of targets to simplify testing, backwards compatible naming probably still works fine

### CODE REVIEW

**Comment by oshai** [comment]
Thanks for the PR, I will wait for the official release to merge 1.4 changes, but thanks for the heads up and effort.

**Comment by oshai** [comment]
@rnentjes please let me know if you want to update the change and merge it, now that 1.4 is out.

**Comment by rnentjes** [comment]
Created a new pull request with the changes for 1.4.0.

**Comment by muzuro** [comment]
Any updates? I think using kotlin-logging force gradle to use 1.3.50 instead of 1.4

**Comment by oshai** [comment]
see #127

**Pull request closed without merging**
