### PR TITLE
added support for same functionality as slf4j-ext.

### PR DESCRIPTION
**Pull request by corneil**
Turns out to get location-aware work as expected I didn't use XLogger. 
Replicated the functionality. I'm not sure if essentially copying the code is legal.

### CODE REVIEW

**Comment by oshai** [comment]
If in any case, we're implementing the xlogger methods by hand, I don't really understand why to create another factory/class/ etc' and not just add new methods to the existing KLogger. I also don't understand why slf4j didn't take that approach. maybe a compatibility issue?
In addition, if there is no js implementation at the moment, maybe we should keep it on the jvm level only?

**Comment by corneil** [comment]
After all this I'm thinking the best may be to just add the `entry`, `exit`, `throwing` and `catching` methods to the existing KLogger. Their presence doesn't add any overhead. We don't need any extra dependencies.

**Comment by corneil** [comment]
As to the JS implementation, I'm not sure how much work is involved in logging the method name for entry / exit

**Comment by oshai** [comment]
Sounds good!

**Comment by oshai** [comment]
Its ok to start with jvm-only version.

**Comment by corneil** [comment]
You can reject/close this PR.

**Pull request closed without merging**
