### PR TITLE
Make macos logger as copy of linux logger

### PR DESCRIPTION
**Pull request by alekseytomin**
If you use kotlin 1.4 - you can merge macos and linux (and minGW - I'm doing it later)

### CODE REVIEW

**Comment by oshai** [comment]
Thanks for the PR!
I am not sure I understood your comment. If we upgrade to Kotlin 1.4 this code is mostly redundant?
If so, I think it's better to upgrade to 1.4 first and then add only the required parts.
In addition, I think we didn't manage to publish linux artefacts yet, in case you have insights about that.

**Comment by alekseytomin** [comment]
On 1.4 You can merge linux/macos/mingw in the one source - https://kotlinlang.org/docs/reference/whatsnew14.html#sharing-code-in-several-targets-with-the-hierarchical-project-structure

**Comment by oshai** [comment]
ok, then see #127. we will merge it before this PR.

**Comment by alekseytomin** [comment]
Replaced by https://github.com/MicroUtils/kotlin-logging/pull/131

**Pull request closed without merging**
