### PR TITLE
Support JS-IR backend

### LINKED ISSUE #126: IR backend
1.4.0 is out! Time to compile this in BOTH mode.

### PR DESCRIPTION
**Pull request by nunocastromartins**
Adds builds for the brower and NodeJS.

Enables JS-IR (with `both` mode).

Should fix #126.

### CODE REVIEW

**Comment by nunocastromartins** [comment]
Hey, @oshai, did this fail because `CHROME_BIN` is not defined? I don't think I can see the logs.

**Comment by oshai** [comment]
This is the error I see:
```
> Task :jsLegacyTestPackageJson
> Task :rootPackageJson
warning workspace-aggregator-e368c2bb-cab0-4a2b-afd1-d3c59b041bdf > kotlin-logging-jsLegacy-test > mocha > yargs-unparser > flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
Error: Couldn't find package "kotlin-logging-jsIr@1.11.3-SNAPSHOT" required by "kotlin-logging-jsIr-test@1.11.3-SNAPSHOT" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/travis/.gradle/yarn/yarn-v1.22.4/lib/cli.js:721:66)
    at new MessageError (/home/travis/.gradle/yarn/yarn-v1.22.4/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/home/travis/.gradle/yarn/yarn-v1.22.4/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/home/travis/.gradle/yarn/yarn-v1.22.4/lib/cli.js:310:30)
    at /home/travis/.gradle/yarn/yarn-v1.22.4/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
> Task :kotlinNpmInstall FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':kotlinNpmInstall'.
>                 Process 'Resolving NPM dependencies using yarn' returns 1
                  
                  yarn install v1.22.4
  [1/4] Resolving packages...
  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 14s
13 actionable tasks: 5 executed, 8 up-to-date
```

**Comment by nunocastromartins** [comment]
Ok, I had that on my machine and cleaning the build fixed it. Any way you can clean Travis' build and rebuild?

**Comment by oshai** [comment]
I will try to add a clean to the build, but I think it is doing it anyway.

**Comment by nunocastromartins** [comment]
Do you get that on your machine as well?

**Comment by nunocastromartins** [comment]
Btw, I noticed that you changed the Travis config to always clean, I just meant that I had to clean it once, not everytime.

**Comment by nunocastromartins** [comment]
Since the other PR passed, I removed the changes I'd added thinking it was failing due to testing in Chrome. Let's see if it passes now without `gradlew clean`, since your PR should have cleaned the build.

**Comment by nunocastromartins** [comment]
Added the `clean` as well, if it passes I'll then remove it to see if it continues passing or whether the `clean` is **really** needed.

**Comment by nunocastromartins** [comment]
Okay, no clue why this is failing now, as yours passed. But I'd experiment removing the `clean` on your PR and see if it continues passing, because on my machine I only needed to clean once and subsequent builds were fine.

**Pull request merged**
