### PR TITLE
Bump to Kotlin 1.5

### PR DESCRIPTION
**Pull request by snooze92**
Kotlin 1.5 is out, but kotlin-logging still being on 1.4 causes dependency conflicts in my project. With this change, I bump the Kotlin version to 1.5.

https://blog.jetbrains.com/kotlin/2021/05/kotlin-1-5-0-released/

### CODE REVIEW

**Comment by snooze92** [comment]
Hey @oshai you seem like the main contributer here. Let me know if I should do anything in particular, in terms of workflow or checks!

I wasn't sure: should I manually bump the version from `2.0.8`? If so, would we want `2.0.9` or `2.1.0`?

**Comment by oshai** [comment]
@snooze92 Thanks! No need to change the version. I still have to figure out publishing to maven central (#177) to be able to merge+publish the lib.

**Comment by snooze92** [comment]
Any news on this or #177? Can I help with either?

**Comment by oshai** [comment]
I managed to get some progress on #177 . It looks like both jcenter was removed and travis project needs migration to `.com` domain. I am still working on it (on another open source project) so it will take few more days. If I'll have anything concrete I will post here. Thanks!

**Comment by oshai** [comment]
ok, I been able to release with #177 , if you can rebase this PR I will merge it.

**Comment by snooze92** [comment]
Rebased. Exciting!

Is my understanding correct that you bump versions in a separate commit?

**Comment by oshai** [comment]
I will bump the version once merged.

Right now the build fails with the following error:
```
> Task :linkDebugTestLinuxX64
e: Compilation failed: /home/travis/.konan/kotlin-native-prebuilt-linux-1.5.10/konan/nativelib/3943150717307232865/libllvmstubs.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/.konan/kotlin-native-prebuilt-linux-1.5.10/konan/nativelib/3943150717307232865/libllvmstubs.so)
 * Source files: 
 * Compiler version info: Konan: 1.5.10 / Kotlin: 1.5.10
 * Output kind: PROGRAM

e: java.lang.UnsatisfiedLinkError: /home/travis/.konan/kotlin-native-prebuilt-linux-1.5.10/konan/nativelib/3943150717307232865/libllvmstubs.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/.konan/kotlin-native-prebuilt-linux-1.5.10/konan/nativelib/3943150717307232865/libllvmstubs.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at kotlinx.cinterop.JvmUtilsKt.loadKonanLibrary(JvmUtils.kt:119)
	at llvm.llvm.<clinit>(llvm.kt:6039)
	at org.jetbrains.kotlin.backend.konan.llvm.BitcodePhasesKt$contextLLVMSetupPhase$1.invoke(BitcodePhases.kt:34)
	at org.jetbrains.kotlin.backend.konan.llvm.BitcodePhasesKt$contextLLVMSetupPhase$1.invoke(BitcodePhases.kt:28)
	at org.jetbrains.kotlin.backend.konan.KonanLoweringPhasesKt$makeKonanModuleOpPhase$1.invoke(KonanLoweringPhases.kt:63)
	at org.jetbrains.kotlin.backend.konan.KonanLoweringPhasesKt$makeKonanModuleOpPhase$1.invoke(KonanLoweringPhases.kt:61)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:94)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:23)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:94)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:30)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:94)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:23)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:94)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:30)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:94)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:41)
	at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:29)
```

Can you please take a look?

**Comment by snooze92** [comment]
Oh damn - will try to reproduce this failure locally and fix, yes!

**Comment by oshai** [comment]
Thanks for the PR, I changed to latest version 1.5.21 and the build passed. Also upgraded dokka and change api level to 1.4 - in order to support using older kotlin version by lib users.

**Comment by snooze92** [comment]
Awesome - thank you so much for following up, I'm sorry I didn't get to it myself on time!

**Pull request merged**
